config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resource :session, only: [:new, :create]
  resources :bands do # This generates a /bands/:band_id/albums route.
    resources :albums, only: [:new]
  end
  resources :albums
end

app/models/album.rb
class Album < ApplicationRecord
  validates :title, :year, presence: true
  validates :category, :inclusion => {:in => ['studio', 'live']}, presence: true

  belongs_to :band,
  primary_key: :id,
  foreign_key: :band_id,
  class_name: :Band
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence:true

  has_many :albums,
  primary_key: :id,
  foreign_key: :band_id,
  class_name: :Album
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence:true
  validates :session_token, presence: true, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil:true}
  after_initialize :ensure_session_token

  attr_reader :password

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    user && user.is_password?(password) ? user : nil
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::password.create(password)
  end

  def is_password?(password)
    BCrypt::password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
    if params.has_key?(:album_id)
      @albums = Album.where(album_id: params[:album_id])
    else
      @albums = Album.all
    end

    render json:@albums
  end

  def index
    @albums = Album.all
    render :index
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  # def new
  #   @album = Album.new
  #   render :new
  # end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def update
    @album = Album.find(params[:id])
    if @album.update_attributes(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to albums_url
  end

  private
    def album_params
      params.require(:album).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def log_in_user!(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def log_out_user!
    current_user.reset_session_token!
    session[:session_token] = nil
    @current_user = nil
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

private
  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )

    if @user
      log_in_user!(@user)
      redirect_to :users_url
    else
      flash.now[:errors] = ['Invalid Login']
      render :new
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if user.save
      redirect_to user_url(@user)
    else
      flash.now(errors) << @user.errors.full_messages
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_form.html.erb
<% action = (album.persisted? ? album_url(album) : albums_url) %>
<% method = (album.persisted? ? :patch : :post) %>

<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>"
    >
  <label for="album_title">Title</label>
  <input
    type="text"
    name="album[title]"
    id="album_title"
    value="<%= album.title %>">

  <% submit_text = (album.persisted? ? 'Update' : 'Create') + ' album!' %>
  <input type="submit" value="<%= submit_text %>">
</form>

app/views/albums/edit.html.erb
<h1>Edit My Album</h1>

<%= render 'form', album: @album %>

app/views/albums/index.html.erb
<h1>All Albums in Inventory</h1>

<ul>
  <% @albums.each do |album| %>
    <li><a href="<%= album_url(album) %>"><%= album.title %></a></li>
  <% end %>
</ul>

<a href="<%= new_album_url %>">Create Album</a>

app/views/albums/new.html.erb
<h1>Add New Album</h1>

<%= render 'form', album: @album %>

app/views/albums/show.html.erb
<h1><%= @album.name %></h1>

<table>
  <!-- <tr>
    <th>Attribute</th>
    <th>Value</th>
  </tr> -->
</table>

<!-- <a href="<%= edit_album_url(@album) %>">Edit <%= @album.name %></a> -->

<form class="" action="<%= edit_album_url(@album) %>" method="get">
  <input type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>"
    >
  <input type="submit" name="" value="Edit">
</form>

<form class="" action="<%= album_url(@album) %>" method="post">
  <input type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>"
    >
  <input type="hidden" name="_method" value="delete">
  <input type="submit" name="" value="Delete">
</form>

app/views/bands/_form.html.erb
<% action = (band.persisted? ? band_url(band) : bands_url) %>
<% method = (band.persisted? ? :patch : :post) %>

<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>"
    >
  <label for="band_name">Name</label>
  <input
    type="text"
    name="band[name]"
    id="band_name"
    value="<%= band.name %>">

  <% submit_text = (band.persisted? ? 'Update' : 'Create') + ' band!' %>
  <input type="submit" value="<%= submit_text %>">
</form>

app/views/bands/edit.html.erb
<h1>Edit My Band</h1>

<%= render 'form', band: @band %>

app/views/bands/index.html.erb
<h1>All Bands in Inventory</h1>

<ul>
  <% @bands.each do |band| %>
    <li><a href="<%= band_url(band) %>"><%= band.name %></a></li>
  <% end %>
</ul>

<a href="<%= new_band_url %>">Create Band</a>

app/views/bands/new.html.erb
<h1>Add New Band</h1>

<%= render 'form', band: @band %>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

<table>
  <!-- <tr>
    <th>Attribute</th>
    <th>Value</th>
  </tr> -->
</table>

<!-- <a href="<%= edit_band_url(@band) %>">Edit <%= @band.name %></a> -->

<form class="" action="<%= edit_band_url(@band) %>" method="get">
  <input type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>"
    >
  <input type="submit" name="" value="Edit">
</form>

<form class="" action="<%= band_url(@band) %>" method="post">
  <input type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>"
    >
  <input type="hidden" name="_method" value="delete">
  <input type="submit" name="" value="Delete">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<header style="font-family:Verdana">
  Music App
</header>
  <body>
    <h3 style="display: flex; justify-content: flex-end;">
    <% if logged_in? %>
    Your account: <%= current_user.email %>
      <form action="<%= session_url %>" method="post">
        <input
          type="hidden"
          name="authenticity_token"
          value="<%= form_authenticity_token %>"
          >
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="Sign out">
      </form>
    <% else %>
    <a style="background-color:pink;border-radius: 25px;padding:10px"
     href="<%= new_session_url %>">Sign In</a>
     <br>
    <a style="background-color:pink;border-radius: 25px;padding:10px"
     href="<%= new_user_url %>">Sign Up</a>
    <% end %></h3>

    <%= yield %>

  </body>
</html>

app/views/users/_form.html.erb
<% if type == :new %>
  <% button_val = "Create Account" %>
  <% action_url = users_url %>
<% elsif type == :edit %>
  <% button_val = "Update" %>
  <% action_url = user_url(user) %>
<% elsif type == :login %>
  <% button_val = "Login" %>
  <% action_url = session_url %>
<% end%>


<form action="<%= action_url %>" method="post">
  <% if type == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="email">Email:</label>
  <input type="text" id="email" name="user[email]"
  value="<%= user.email %>">
  <br><br>

  <label for="password">Password:</label>
  <input type="password" id="password" name="user[password]">
  <br><br>

  <input type="submit" value="<%= button_val %>">
</form>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render('form', {user:@user, type: :new}) %>